"""create manufacturers and link to products

Revision ID: 02e0c951b616
Revises: c4e8bed11dcd
Create Date: 2026-08-24 11:32:21.678341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02e0c951b616'
down_revision: Union[str, Sequence[str], None] = 'c4e8bed11dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('products', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'products', 'manufacturers', ['manufacturer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'manufacturer_id')
    op.drop_table('manufacturers')
    # ### end Alembic commands ###
