"""add subcategory_id to products

Revision ID: 242cc41d3353
Revises: b82313473c41
Create Date: 2026-08-19 11:43:41.880713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '242cc41d3353'
down_revision: Union[str, Sequence[str], None] = 'b82313473c41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_products_subcategory_id', 'products', 'subcategories', ['subcategory_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_products_subcategory_id', 'products', type_='foreignkey')
    op.drop_column('products', 'subcategory_id')
    # ### end Alembic commands ###
