"""add image to subcategories

Revision ID: 3a246e6caff5
Revises: 242cc41d3353
Create Date: 2026-08-19 12:21:54.190259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a246e6caff5'
down_revision: Union[str, Sequence[str], None] = '242cc41d3353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategories', sa.Column('image', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subcategories', 'image')
    # ### end Alembic commands ###
