"""add promo codes

Revision ID: 5900780bbfe7
Revises: 0056f2fd13e6
Create Date: 2026-08-19 11:31:46.151328

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5900780bbfe7"
down_revision: str | Sequence[str] | None = "0056f2fd13e6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

promo_discount_type = sa.Enum(
    "PERCENTAGE",
    "FIXED_AMOUNT",
    name="promo_discount_type",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "promo_codes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("discount_type", promo_discount_type, nullable=False),
        sa.Column("discount_value", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column(
            "minimum_order_value", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=True),
        sa.Column("valid_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("usage_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column("max_uses", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(discount_type = 'PERCENTAGE' "
            "AND discount_value > 0 "
            "AND discount_value <= 1) "
            "OR (discount_type = 'FIXED_AMOUNT' "
            "AND discount_value > 0)",
            name="check_promo_discount_value",
        ),
        sa.CheckConstraint(
            "max_uses IS NULL OR max_uses > 0", name="check_promo_max_uses"
        ),
        sa.CheckConstraint(
            "minimum_order_value IS NULL OR minimum_order_value >= 0",
            name="check_promo_minimum_order_value",
        ),
        sa.CheckConstraint("usage_count >= 0", name="check_promo_usage_count"),
        sa.CheckConstraint(
            "valid_from IS NULL OR valid_until IS NULL OR valid_from <= valid_until",
            name="check_promo_validity_dates",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promo_codes_code"), "promo_codes", ["code"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_promo_codes_code"), table_name="promo_codes")
    op.drop_table("promo_codes")
    promo_discount_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
