"""add HSQLDB reservation synchronization

Revision ID: 81dff29f4416
Revises: 96caca3e53dd
Create Date: 2026-09-01 13:19:00.864777

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "81dff29f4416"
down_revision: str | Sequence[str] | None = "96caca3e53dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hsqldb_reservations",
        sa.Column(
            "source_position_id",
            sa.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("instance_id", sa.Integer(), nullable=False),
        sa.Column("begin_at", sa.DateTime(), nullable=True),
        sa.Column("end_at", sa.DateTime(), nullable=True),
        sa.Column("source_status", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["instance_id"], ["instances.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("source_position_id"),
    )
    op.create_index(
        "ix_hsqldb_reservations_instance_dates",
        "hsqldb_reservations",
        ["instance_id", "begin_at", "end_at"],
        unique=False,
    )
    op.add_column(
        "instances",
        sa.Column("hsqldb_inventory_code", sa.String(length=50), nullable=True),
    )
    op.create_unique_constraint(
        "uq_instances_hsqldb_inventory_code",
        "instances",
        ["hsqldb_inventory_code"],
    )
    op.add_column(
        "products", sa.Column("hsqldb_name", sa.String(length=255), nullable=True)
    )
    op.create_unique_constraint(
        "uq_products_hsqldb_name",
        "products",
        ["hsqldb_name"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_products_hsqldb_name",
        "products",
        type_="unique",
    )
    op.drop_column("products", "hsqldb_name")
    op.drop_constraint(
        "uq_instances_hsqldb_inventory_code",
        "instances",
        type_="unique",
    )
    op.drop_column("instances", "hsqldb_inventory_code")
    op.drop_index(
        "ix_hsqldb_reservations_instance_dates",
        table_name="hsqldb_reservations",
        if_exists=True,
    )
    op.drop_table("hsqldb_reservations")
    # ### end Alembic commands ###
