"""make columns not null

Revision ID: 898f15c0653b
Revises: 5cadb342fe8b
Create Date: 2026-07-28 12:17:41.467775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '898f15c0653b'
down_revision: Union[str, Sequence[str], None] = '5cadb342fe8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('instances', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'MAINTENANCE', 'BROKEN', 'RETIRED', name='instancestatus'),
               nullable=False,
               existing_server_default=sa.text("'AVAILABLE'::instancestatus"))
    op.alter_column('product_images', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product_images', 'display_order',
               existing_type=sa.SMALLINT(),
               nullable=False)
    op.alter_column('product_sizes', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('product_sizes', 'size',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('products', 'visibility_status',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'visibility_status',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('products', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('product_sizes', 'size',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('product_sizes', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('product_images', 'display_order',
               existing_type=sa.SMALLINT(),
               nullable=True)
    op.alter_column('product_images', 'alt_text',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('product_images', 'image',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('instances', 'status',
               existing_type=postgresql.ENUM('AVAILABLE', 'MAINTENANCE', 'BROKEN', 'RETIRED', name='instancestatus'),
               nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::instancestatus"))
    op.alter_column('categories', 'slug',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
