"""change favorite to product_slug

Revision ID: 987f483293d7
Revises: df5516f1fa2e
Create Date: 2026-07-28 15:24:16.724307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '987f483293d7'
down_revision: Union[str, Sequence[str], None] = 'df5516f1fa2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('product_slug', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('favorites_product_id_fkey'), 'favorites', type_='foreignkey')
    op.create_foreign_key(None, 'favorites', 'products', ['product_slug'], ['slug'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('favorites', 'product_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorites', sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.create_foreign_key(op.f('favorites_product_id_fkey'), 'favorites', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('favorites', 'product_slug')
    # ### end Alembic commands ###
