"""add loyalty points expiration

Revision ID: 9bd1a399768c
Revises: cbcd56097ca8
Create Date: 2026-09-02 10:51:16.308759

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bd1a399768c"
down_revision: Union[str, Sequence[str], None] = "cbcd56097ca8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "loyalty_transactions",
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("loyalty_transactions", "expires_at")
    # ### end Alembic commands ###
