"""add promo_code_id to orders

Revision ID: d547c3f3c908
Revises: dfc9d79dd1ed
Create Date: 2026-08-25 16:09:54.936283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd547c3f3c908'
down_revision: Union[str, Sequence[str], None] = 'dfc9d79dd1ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('promo_code_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_orders_promo_code_id'), 'orders', ['promo_code_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'promo_codes', ['promo_code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_promo_code_id'), table_name='orders')
    op.drop_column('orders', 'promo_code_id')
    # ### end Alembic commands ###
