"""add loyalty transactions

Revision ID: d8c43f1c3890
Revises: c4e8bed11dcd
Create Date: 2026-08-21 12:41:02.599365

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d8c43f1c3890"
down_revision: str | Sequence[str] | None = "c4e8bed11dcd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

loyalty_transaction_type = sa.Enum(
    "EARN",
    "SPEND",
    "REFUND",
    "REVERSAL",
    "ADJUSTMENT",
    name="loyalty_transaction_type",
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "loyalty_transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("type", loyalty_transaction_type, nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(type IN ('EARN', 'REFUND') AND amount > 0) "
            "OR (type IN ('SPEND', 'REVERSAL') AND amount < 0) "
            "OR (type = 'ADJUSTMENT' AND amount <> 0)",
            name="check_loyalty_transaction_amount_sign",
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "order_id", "type", name="uq_loyalty_transaction_order_type"
        ),
    )
    op.create_index(
        "ix_loyalty_transactions_user_created_at",
        "loyalty_transactions",
        ["user_id", "created_at", "id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_loyalty_transactions_user_created_at", table_name="loyalty_transactions"
    )
    op.drop_table("loyalty_transactions")
    loyalty_transaction_type.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
